# Generated by Django 4.0.6 on 2022-08-02 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dtm_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="DTM Created"),
                ),
                (
                    "dtm_updated",
                    models.DateTimeField(auto_now=True, verbose_name="DTM Updated"),
                ),
                (
                    "route",
                    models.CharField(blank=True, default=None, max_length=8, null=True),
                ),
                (
                    "registration",
                    models.CharField(
                        blank=True, default=None, max_length=10, null=True
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "whatsapp",
                    models.URLField(
                        blank=True, default=None, max_length=128, null=True
                    ),
                ),
                ("data", models.JSONField(blank=True, default=None, null=True)),
                (
                    "attendant",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="route_attendant",
                        to="apps.person",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="route_driver",
                        to="apps.person",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="route_bus_parent",
                        to="apps.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bus Route",
                "ordering": ["route", "id"],
            },
        ),
        migrations.CreateModel(
            name="BusRider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dtm_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="DTM Created"),
                ),
                (
                    "dtm_updated",
                    models.DateTimeField(auto_now=True, verbose_name="DTM Updated"),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True
                    ),
                ),
                ("time", models.TimeField(blank=True, default=None, null=True)),
                (
                    "rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="apps.person"
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="route_riders",
                        to="transport.busroute",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bus Rider",
                "ordering": ["route", "rider"],
                "unique_together": {("route", "rider")},
            },
        ),
    ]
