# Generated by Django 4.0.6 on 2022-08-01 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dtm_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="DTM Created"),
                ),
                (
                    "dtm_updated",
                    models.DateTimeField(auto_now=True, verbose_name="DTM Updated"),
                ),
                ("last_name", models.CharField(max_length=32)),
                (
                    "first_name",
                    models.CharField(
                        blank=True, default=None, max_length=32, null=True
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("faculty", "Faculty"),
                            ("staff", "Staff"),
                            ("other", "Other"),
                        ],
                        default="student",
                        max_length=8,
                    ),
                ),
                ("grade", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=16,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?[1-9]\\d{4,14}$",
                            )
                        ],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default=None, max_length=254, null=True
                    ),
                ),
                ("address", models.TextField(blank=True, default=None, null=True)),
                ("address_city", models.CharField(default="Pune", max_length=32)),
                (
                    "address_pincode",
                    models.CharField(blank=True, default=None, max_length=6, null=True),
                ),
                ("address_country", models.CharField(default="IN", max_length=2)),
                ("is_student", models.BooleanField(default=True)),
                ("is_teacher", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "person",
                "unique_together": {
                    ("first_name", "last_name"),
                    ("first_name", "last_name", "phone"),
                    ("first_name", "last_name", "email"),
                },
            },
        ),
    ]
